### ISSUE TITLE
Consider having more recent OpenBLAS shipped with scipy wheel

### ISSUE THREAD

**Issue by lesteve** [colesbury/nogil-install#2]
Currently the Scipy wheel still contains an old OpenBLAS since it uses openblas-devel here (which I think is OpenBLAS 0.3.3): https://github.com/colesbury/nogil-install/blob/master/pip/scipy.sh

I think this is one of the reason we were seeing sporadic segmentation faults in our scikit-learn CI with the nogil: https://github.com/scikit-learn/scikit-learn/issues/23786.

I am guessing using  scipy `tools/openblas_support.py` could be done similarly to what is done for the nogil numpy build here?
https://github.com/colesbury/nogil-install/blob/master/pip/preinstall-openblas.sh

It seems like scipy 1.8 ships OpenBLAS 1.7:
https://github.com/scipy/scipy/blob/maintenance/1.8.x/tools/openblas_support.py

and scipy 1.9 (not yet released) will ship OpenBLAS 1.8:
https://github.com/scipy/scipy/blob/maintenance/1.9.x/tools/openblas_support.py

**Comment by colesbury** [comment]
I've re-built SciPy 1.8.0 (and also 1.8.1) with OpenBLAS 1.7 (using `tools/openblas_support.py`).

I'm not sure why, but the OpenBLAS library still doesn't look identical to the one used upstream:
nogil: libopenblasp-r0-2d23e62b.3.17.so
upstream: libopenblasp-r0-8b9e111f.3.17.so

**Comment by lesteve** [comment]
Thanks a lot, I think this should be enough to avoid issues in our CI (and potentially avoid issues to other people in some weird edge cases).

I don't know enough about wheels to have guesses about why the .so name may differ. I would say that as long as the OpenBLAS version is the same, this should be fine ...
